name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set homepage in package.json
        run: |
          jq '.homepage = "https://kennethdoerflein.github.io/Tic-Tac-Toe-React/"' package.json > temp.json && mv temp.json package.json

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch to deploy to
          folder: build # The folder to deploy
