name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Overwrite next.config.ts for GitHub Pages
        run: |
          cat > next.config.ts <<EOF
          import type { NextConfig } from "next";

          const nextConfig: NextConfig = {
            output: "export",
            trailingSlash: true,
            basePath: "/Tic-Tac-Toe-React",
            assetPrefix: "/Tic-Tac-Toe-React/",
          };

          export default nextConfig;
          EOF

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Disable Jekyll
        run: |
          touch out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch to deploy to
          folder: out/ # The folder to deploy
